image: rust:1.32

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .cargo-registry/
    - target/

before_script:
    - rustup component add clippy
    - mkdir -p .cargo-registry

stages:
    - check

check:
    stage: check
    script:
        - cargo build --release
        - cargo test --release
        - cargo clippy -- -D warnings
