[package]
name = "slacks"
version = "0.2.1"
authors = ["sameyasu <sameyasu@gmail.com>"]

[dependencies]
docopt = "*"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
reqwest = "0.9.5"
regex = "1"
